routes/web.php
<?php



Route::get('/', function () {
    return view('welcome'); //RETORNARA VER ESTE MENSAJE DE BIENVENIDA
});

  //vistas generales parte frontend del proyecto
  Route::get('/','FrontController@index'); //CREAMOS LA RUTA DEL INDEX Y HACEMOS REFERENCIA AL CONTROLADOR Y SU METODO LLAMADO INDEX
  Route::get('contacto','FrontController@contacto'); //SE VA AL METODO CONTACTO
  Route::get('reviews','FrontController@reviews'); //SE VA AL METODO REWIES
  Route::get('admin','FrontController@admin'); //SE IRA AL METODO DEL ADMINISTRADOR EL PRIMER ADMIN ES PARA LLAMAR LA VISTA EN LA RUTA localhost/admin

//USUARIO RUTAS
  //hacemos un enrutador RESOUCE para el CRUD crear usuario
  Route::resource('usuario', 'UsuarioController'); //http://localhost:8000/usuario/create  se llama asi es un resouce y la llama automaticamente los metodos

  //especificamos las rutas de la autentificacion hicimos un resouce
  Route::resource('log', 'LogController');
  Route::get('logout','LogController@logout'); //creamos la ruta para cerrar Session
  //declaramos una ruta logaout vamos a usar el LogController y es pecificamos el metodo logout y crearemos este metodo en el controlador

  //GENERO RUTAS
  //para el AJAX en la creacion de  para el generocontroller su ruta
  Route::resource('genero', 'GeneroController'); //http://localhost:8000/genero/create
  //Route::get('generos', 'GeneroController@listing'); //para listar en el index, es lo mismo que en el metodo index del controlador para usar AJAX

  //PELICULAS RUTAS
    Route::resource('pelicula', 'MovieController');

  //MAIL RUTAS
  Route::resource('mail', 'MailController');

  //RESETEO DE CUENTAS, RESTABLECER PASSWORD
  //SE CREAN AUTOMATICAMENTE LAS SIGUIENTES LINEAS EN LA autentificacion CUANDO USAMOS VER DOCUMENTACION

Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/pelicula/create.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.request')
    {{--especificamos la ruta y el metodo que sera enviado el formulario, y el atributo para manejar ARCHIVOS para subir es el files true --}}
		  	{!!Form::open(['route'=>'pelicula.store', 'method'=>'POST','files' => true])!!} {{-- FILES TRUE PARA SUBIR ARCHIVOS--}}

		  		@include('pelicula.forms.pelicula'){{--incluimos la subvista donde esta el cuerpo del formulario--}}

				{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
			{!!Form::close()!!}
	@endsection

resources/views/pelicula/edit.blade.php
@extends('layouts.admin')
	@section('content')

		{!!Form::model($movie,['route'=> ['pelicula.update',$movie->id],'method'=>'PUT','files' => true])!!} {{--agregamos files true para los archivos, lo demas es lo mismo al anterior--}}

    	@include('pelicula.forms.pelicula')  {{--incluimos el formulario de editar los campos que se llenaran con el model--}}

			{!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
		{!!Form::close()!!}

		{!!Form::open(['route'=> ['pelicula.destroy',$movie->id],'method'=>'DELETE'])!!}
			{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
		{!!Form::close()!!}
	 @endsection

resources/views/pelicula/index.blade.php
@extends('layouts.admin')
	@include('alerts.success')
	@section('content')

		<table class="table" id="myTable">
			<thead>
				<th>Nombre</th>
				<th>Genero</th>
				<th>Direccion</th>
				<th>Caratula</th>
				<th>Operaciones</th>
			</thead>

			{{--recorremos la variable movies2 en la variabble que creamos moviex--}}
			@foreach($movies2 as $moviex)
				<tbody>
					<td>{{$moviex->name}}</td> 	{{--mostramos del movie2 que trae del modelo MOVIE su nombre--}}
					<td>{{$moviex->genre}}</td>	{{--mostramos del movie2 que trae del modelo MOVIE su GENRE GRACIAS A LA CONSULTA--}}
					<td>{{$moviex->direction}}</td>	{{--mostramos del movie2 que trae del modelo MOVIE su direccion--}}
					<td> {{--aca contruimos la imgaen esta en la carpeta movies y especificamos moviex le pasamos el path que esta en la base de datos--}}
						<img src="movies/{{$moviex->path}}" alt="" style="width:100px;"/>{{--mostramos del movie2 que trae del modelo MOVIE su IMAGEN--}}
					</td>
					<td>
						{!!link_to_route('pelicula.edit', $title = 'Editar', $parameters = $moviex->id, $attributes = ['class'=>'btn btn-primary'])!!}
					</td>
				</tbody>
			@endforeach
		</table>
		{{--rendereamos la paginacion para que pueda mostrar de la  que contiene la variable de todos los usuarios, tiene el listado de todos los usuarios--}}
		{{-- {!!$moviespag->render()!!} --}}
	@endsection